### ISSUE TITLE
[Question] Work Sans font included?

### ISSUE THREAD

**Issue by mjsevilla** [mvanlonden/grommet-css#2]
Hi, I'm looking to use Grommet-cli in my web app I've started with create-react-app. I've also included your grommet-css which sounds like it's supposed to bring the grommet scss support to create-react-app. Is the work sans font that is used in grommet included in this package? Or is there additional imports I need to add for the font? Thanks!

**Comment by mvanlonden** [comment]
Grommet comes with a built css file if you rather not build the scss in your project. This repo is intended to serve as a standalone theming repository if you'd like to maintain your own theme. Otherwise I would just `import 'grommet/grommet.min.css'`. That said, the font should automatically be loaded by the css.
